version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: intro_db
      MYSQL_USER: alx_client
      MYSQL_PASSWORD: alx_pass
    volumes:
      - mysql-data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d
    networks:
      - my-net
  app:
    build: .
    container_name: my-app
    depends_on:
      - db
    environment:
      - DB_HOST=my-mysql
      - DB_USER=alx_client
      - DB_PASSWORD=alx_pass
      - DB_NAME=intro_db
    networks:
      - my-net
volumes:
  mysql-data:
networks:
  my-net:
